# Pandas užduotys 2

In [3]:
import numpy as np
import pandas as pd

#  1 Sulipdykite iš 4 fragmentų vieną lentelę:

fragmentus rasite [čia](https://github.com/robotautas/kursas/tree/master/Pandas/tops)

* top_left = pd.read_csv('top1-25-1.csv')
* top_right = pd.read_csv('top1-25-2.csv')
* bottom_left = pd.read_csv('top26-50-1.csv')
* bottom_right = pd.read_csv('top26-50-2.csv')

pirmiausiai sujunkite apatinę dalį, tada viršutinę *(yra persidengiančių stulpelių!)*, galiausiai viršų su apačia. Naudokite **.concat()** ir **.merge()** metodus.

In [10]:
top_left = pd.read_csv('tops/top1-25-1.csv')
top_right = pd.read_csv('tops/top1-25-2.csv')
bottom_left = pd.read_csv('tops/top26-50-1.csv')
bottom_right = pd.read_csv('tops/top26-50-2.csv')
data_bottom = pd.concat([bottom_left, bottom_right], axis=1)
data_top = pd.merge(top_left, top_right, on=['Track.Name', 'Popularity'])
data = pd.concat([data_top, data_bottom], sort=False)

In [11]:
data.head()

,Track.Name,Artist.Name,Genre,Popularity,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.
0,Senorita,Shawn Mendes,canadian pop,79.0,117,55,76,-6,8,75,191,4,3
1,China,Anuel AA,reggaeton flow,92.0,105,81,79,-4,8,61,302,8,9
2,boyfriend (with Social House),Ariana Grande,dance pop,85.0,190,80,40,-4,16,70,186,12,46
3,Beautiful People (feat. Khalid),Ed Sheeran,pop,NaN,93,65,64,-8,8,55,198,12,19
4,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,94.0,150,65,58,-4,11,18,175,45,7

# 2 Sutvarkykite indeksą - padarykite, kad prasidėtų nuo 1.

In [14]:
data['#']=list(range(1, 51))

In [15]:
data.set_index('#', inplace=True)

In [16]:
data.head()

,Track.Name,Artist.Name,Genre,Popularity,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.
#,,,,,,,,,,,,,
1,Senorita,Shawn Mendes,canadian pop,79.0,117,55,76,-6,8,75,191,4,3
2,China,Anuel AA,reggaeton flow,92.0,105,81,79,-4,8,61,302,8,9
3,boyfriend (with Social House),Ariana Grande,dance pop,85.0,190,80,40,-4,16,70,186,12,46
4,Beautiful People (feat. Khalid),Ed Sheeran,pop,NaN,93,65,64,-8,8,55,198,12,19
5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,94.0,150,65,58,-4,11,18,175,45,7

# 3 Sukurkite grupavimo pagal žanrą objektą

In [40]:
grouped = data.groupby('Genre')

In [44]:
# data[data['Energy'] >= 80].head()
grouped

# 4 kokie žanrai lentelėje pasitaiko daugiau negu 3 kartus?

In [45]:
newdf = grouped.count()

In [46]:
newdf.head()

,Track.Name,Artist.Name,Popularity,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.
Genre,,,,,,,,,,,,
atl hip hop,1,1,1,1,1,1,1,1,1,1,1,1
australian pop,1,1,1,1,1,1,1,1,1,1,1,1
big room,1,1,1,1,1,1,1,1,1,1,1,1
boy band,1,1,1,1,1,1,1,1,1,1,1,1
brostep,2,2,1,2,2,2,2,2,2,2,2,2

In [47]:
newdf[newdf['Energy']>3]['Energy']

Genre
dance pop    8
latin        5
pop          6
Name: Energy, dtype: int64

# 5 Koks žanras pats populiariausias? Koks mažiausiai populiarus?
(pagal populiarumo vidurkį)

In [49]:
most_popular_genre = grouped['Popularity'].mean().idxmax()
most_popular_score = grouped['Popularity'].mean().max()
least_popular_genre = grouped['Popularity'].mean().idxmin()
least_popular_score = grouped['Popularity'].mean().min()
print(most_popular_genre, most_popular_score)
print(least_popular_genre, least_popular_score)

electropop 95.0
canadian pop 74.5

# 6 Sukurkite lentelę, kurioje matytųsi, koks žanras turi aukščiausią vidurkį kiekviename indikatoriuje, bei pats vidurkis.
kad nereikėtų daug vargti su stulpelių pavadinimais, galima juos ištraukti su **.columns.tolist()**

In [51]:
collums = data.columns.tolist()[3:]
genre = grouped[collums].mean().idxmax()
numbers = grouped[collums].mean().max()
result = pd.DataFrame([collums, genre, numbers],
                      ['Indicator', 'Genre', 'Points']).transpose()

In [52]:
result

          Indicator           Genre Points
0        Popularity      electropop   95.0
1  Beats.Per.Minute      trap music  180.0
2            Energy  reggaeton flow   80.0
3      Danceability  r&b en espanol   88.0
4    Loudness..dB..         brostep   -2.5
5          Liveness         brostep   37.5
6          Valence.        boy band   95.0
7           Length.  reggaeton flow  305.5
8    Acousticness..  australian pop   69.0
9      Speechiness.      electropop   34.0

# 7 Grįžkime prie sulipdytos lentelės. Ištraukite visas eilutes, kurios turi NaN reikšmių.
*filtravimo sąlygose naudokite **.isnull()** funkciją.*

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 1 to 50
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Track.Name        50 non-null     object
 1   Artist.Name       50 non-null     object
 2   Genre             48 non-null     object
 3   Popularity        47 non-null     float64
 4   Beats.Per.Minute  50 non-null     int64
 5   Energy            50 non-null     int64
 6   Danceability      50 non-null     int64
 7   Loudness..dB..    50 non-null     int64
 8   Liveness          50 non-null     int64
 9   Valence.          50 non-null     int64
 10  Length.           50 non-null     int64
 11  Acousticness..    50 non-null     int64
 12  Speechiness.      50 non-null     int64
dtypes: float64(1), int64(9), object(3)
memory usage: 5.5+ KB

In [54]:
data[data['Genre'].isnull() | data['Popularity'].isnull()]

,Track.Name,Artist.Name,Genre,Popularity,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.
#,,,,,,,,,,,,,
4,Beautiful People (feat. Khalid),Ed Sheeran,pop,NaN,93,65,64,-8,8,55,198,12,19
19,Lalala,Y2K,NaN,88.0,130,39,84,-8,14,50,161,18,8
25,bad guy (with Justin Bieber),Billie Eilish,electropop,NaN,135,45,67,-11,12,68,195,25,30
48,Happier,Marshmello,brostep,NaN,100,79,69,-3,17,67,214,19,5
50,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,NaN,82.0,95,79,75,-6,7,61,206,21,12

# 8 Stulpelyje 'Genre' NaN reikšmes pakeiskite į 'pop'

In [55]:
data['Genre']= data['Genre'].fillna('pop')

# 9 Stulpelyje 'Popularity' trūkstamas reikšmes pakeiskite į stulpelio vidurkį

In [56]:
data['Popularity'] = data['Popularity'].fillna(value=data['Popularity'].mean())

In [60]:
data[data['Genre'].isnull() | data['Popularity'].isnull()]
data.head(20)

,Track.Name,Artist.Name,Genre,Popularity,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.
#,,,,,,,,,,,,,
1,Senorita,Shawn Mendes,canadian pop,79.000000,117,55,76,-6,8,75,191,4,3
2,China,Anuel AA,reggaeton flow,92.000000,105,81,79,-4,8,61,302,8,9
3,boyfriend (with Social House),Ariana Grande,dance pop,85.000000,190,80,40,-4,16,70,186,12,46
4,Beautiful People (feat. Khalid),Ed Sheeran,pop,87.489362,93,65,64,-8,8,55,198,12,19
5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,94.000000,150,65,58,-4,11,18,175,45,7
6,I Don't Care (with Justin Bieber),Ed Sheeran,pop,84.000000,102,68,80,-5,9,84,220,9,4
7,Ransom,Lil Tecca,trap music,92.000000,180,64,75,-6,7,23,131,2,29
8,How Do You Sleep?,Sam Smith,pop,90.000000,111,68,48,-5,8,35,202,15,9
9,Old Town Road - Remix,Lil Nas X,country rap,87.000000,136,62,88,-6,11,64,157,5,10
10,bad guy,Billie Eilish,electropop,95.000000,135,43,70,-11,10,56,194,33,38
11,Callaita,Bad Bunny,reggaeton,93.000000,176,62,61,-5,24,24,251,60,31
12,Loco Contigo (feat. J. Balvin & Tyga),DJ Snake,dance pop,86.000000,96,71,82,-4,15,38,185,28,7
13,Someone You Loved,Lewis Capaldi,pop,88.000000,110,41,50,-6,11,45,182,75,3
14,Otro Trago - Remix,Sech,panamanian pop,87.000000,176,79,73,-2,6,76,288,7,20
15,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,92.000000,101,50,83,-4,12,10,205,10,5
16,No Guidance (feat. Drake),Chris Brown,dance pop,82.000000,93,45,70,-7,16,14,261,12,15
17,LA CANCION,J Balvin,latin,90.000000,176,65,75,-6,11,43,243,15,32
18,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,91.000000,90,48,76,-6,7,91,158,56,5
19,Lalala,Y2K,pop,88.000000,130,39,84,-8,14,50,161,18,8
20,Truth Hurts,Lizzo,escape room,91.000000,158,62,72,-3,12,41,173,11,11